services:
  postgres:
    container_name: my_postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: aggregator
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - aggregator-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  migrations:
    build:
      context: .
      dockerfile: Dockerfile.migrations
    container_name: aggregator_migrations
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - aggregator-network
    command: ["Host=postgres;Port=5432;Database=aggregator;Username=postgres;Password=postgres;"]

  aggregator:
    build: .
    container_name: aggregator_app
    depends_on:
      postgres:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    networks:
      - aggregator-network
    volumes:
      - ./parsing_results.txt:/app/parsing_results.txt
    restart: "no"

networks:
  aggregator-network:
    driver: bridge

volumes:
  postgres_data: