version: '3.8'
services:
  postgres:
    container_name: my_postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: aggregator
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - aggregator-network

networks:
  aggregator-network:
    driver: bridge

volumes:
  postgres_data: